In [1]:
a = 'hello'

In [2]:
a

'hello'

In [26]:
for i in range(10):
    print('  '*(i-10)+'*'*(i*2)+' '*(i-10))


**
****
******
********
**********
************
**************
****************
******************


In [16]:
s1= 'aaa bbb ccc'
s2 = 'AAA,BBB,CCC'
s1.split()


['AAA', 'BBB', 'CCC']

In [18]:
s2.split(',')


['AAA', 'BBB', 'CCC']

In [19]:
s1.upper()


'AAA BBB CCC'

In [20]:
s2.lower()


'aaa,bbb,ccc'

In [21]:
s1.endswith('ccc')

True

In [22]:
flds = s1.split()

In [23]:
flds

['aaa', 'bbb', 'ccc']

In [28]:
' xxx '.join(flds)

'aaa xxx bbb xxx ccc'

In [30]:
dir(s1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [31]:
a1=[1,9,-12]
a2=[20,5,-16]
arr = [a1,a2]

In [32]:
arr

[[1, 9, -12], [20, 5, -16]]

In [35]:
arr[0]

[1, 9, -12]

In [36]:
arr[1]

[20, 5, -16]

In [37]:
arr[1][2]

-16

In [39]:
arr[-1]

[20, 5, -16]

In [50]:
A= arr[:]

In [51]:
id(arr)

139846216455944

In [53]:
id(A)

139846216032008

In [54]:
B = arr

In [55]:
id (B)

139846216455944

In [56]:
A is arr

False

In [57]:
B is arr

True

In [4]:
import numpy as np


In [59]:
A = np.array([[1, 9, -12], [20, 5, -16]])

In [60]:
A[1,2]

-16

In [61]:
A.shape

(2, 3)

In [7]:
c = np.zeros((5,3))

In [8]:
c

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
c.shape

(5, 3)

In [14]:
d = c.reshape((15))

In [15]:
d

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.])

In [16]:
e = c.reshape((3,5))

In [17]:
e

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [4]:
list(range(10,1,-2))

[10, 8, 6, 4, 2]

In [10]:
myList = []
for i in range(1,10):
    if i % 2 == 0:
        print('%02d'  %i)
        myList.append(i)
print(myList)

02
04
06
08
[2, 4, 6, 8]


In [13]:
myList = [i*2 for i in range(1,10) if i % 2 ==0]

In [14]:
myList

[4, 8, 12, 16]

In [15]:
list()

[]

In [18]:
a = [1,2,3]
b = ['a','b','c']

In [19]:
for v in zip(a,b):
    print(v)

(1, 'a')
(2, 'b')
(3, 'c')


In [20]:
for i, j in zip(a,b):
    print( i , j )

1 a
2 b
3 c


In [22]:
d = dict()

In [24]:
d

{}

In [25]:
d.keys()

dict_keys([])

In [26]:
d = dict(zip(b,a))

In [27]:
d

{'a': 1, 'b': 2, 'c': 3}

In [28]:
isinstance(d,dict)

True

In [29]:
type(d)

dict

In [32]:
d.items()

dict_items([('a', 1), ('b', 2), ('c', 3)])

In [33]:
d.keys()

dict_keys(['a', 'b', 'c'])

In [34]:
d.values()

dict_values([1, 2, 3])

In [35]:
for k,v in d.items():
    print(k,v)

a 1
b 2
c 3


In [36]:
h = [6,2,5]

In [37]:
h.sort()

In [38]:
h

[2, 5, 6]

In [39]:
g = [6,2,5]

In [40]:
sorted(g)

[2, 5, 6]

In [41]:
g

[6, 2, 5]

In [42]:
gg= sorted(g)

In [43]:
gg

[2, 5, 6]

In [44]:
d['a']

1

In [45]:
d['b']

2

In [46]:
d['c']

3

In [47]:
d['d']

KeyError: 'd'

In [48]:
d.get('d',0)

0

In [51]:
for k in sorted(d.keys()):
    print(k, d[k])

a 1
b 2
c 3


In [52]:
kv = list(d.items())

In [54]:
kv

[('a', 1), ('b', 2), ('c', 3)]

In [61]:
kv.sort(reverse= True)

In [62]:
kv

[('d', 0), ('c', 3), ('b', 2), ('a', 1)]

In [57]:
kv.append(('d',0))

In [58]:
kv

[('c', 3), ('b', 2), ('a', 1), ('d', 0)]

In [59]:
kv.sort()

In [60]:
kv

[('a', 1), ('b', 2), ('c', 3), ('d', 0)]

In [65]:
kv.sort(key=lambda x : x[1])

In [66]:
kv

[('d', 0), ('a', 1), ('b', 2), ('c', 3)]

In [67]:
x = range(10)

In [86]:
y = map(lambda a : a*2 -1.5,x)

In [72]:
list(y)

[-1.5, 0.5, 2.5, 4.5, 6.5, 8.5, 10.5, 12.5, 14.5, 16.5]

In [74]:
type(y)

map

In [87]:
yy = list(y)

In [94]:
import numpy as np
xx = np.array(yy)


In [95]:
xx

array([ -1.5,   0.5,   2.5,   4.5,   6.5,   8.5,  10.5,  12.5,  14.5,  16.5])